backend: [BUG]: SocketIO
I really do not understand why

I tried to run the app in the container

docker exec -it flask-dev sh

```
/app/matcha # python __init__.py
Traceback (most recent call last):
  File "/app/matcha/__init__.py", line 37, in <module>
    SocketIO.run(app)
TypeError: run() missing 1 required positional argument: 'app'
```

Resources:

- https://stackoverflow.com/a/57686577
- https://github.com/miguelgrinberg/Flask-SocketIO/issues/894#issuecomment-460034033
- https://github.com/willthames/docker-debug/blob/master/server.py
- https://github.com/miguelgrinberg/Flask-SocketIO

TODO:

Follow and try this guide

- https://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent

from this repository

- https://github.com/miguelgrinberg/Flask-SocketIO