Revert "take sid from request"
This reverts commit a5578d22a26a8c1ca602c7ae9e1ef6dc4525b3ac.

Error on request:
Traceback (most recent call last):
  File
"/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 370,
in run_wsgi
    execute(self.server.app)
  File
"/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 336,
in execute
    write(b"")
  File
"/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 261,
in write
    assert status_set is not None, "write() before
start_response"
AssertionError: write() before start_response